apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  ScaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydeploy 
  miniReplicas: 3
  maxReplicas: 7
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization 
          averageUtilization: 20
