apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysqldb
  replicas: 1
  selector:
    matchLabels: 
        app: dbdev
  template:
    metadata:
      labels:
        app: dbdev
    spec:
      containers:
        - name: dbcont01
          image: nikhilkotharu/k8s:dbimage
          ports:
            - containerPort: 3306
    
          envFrom:
            - secretRef:
                name: mysec

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          

          volumeMounts:
            - name: pvc-1
              mouthPath: /usr/share/nginx/html/


      volumeClaimTemplates:
          - metadata:
              name: pvc-1
            spec:
              accessModes:
               - ReadWriteOnce
              storageClassName: gp2
               
              resources:
                requests:
                  storage: 2Gi
